In [4]:
import pandas as pd
import numpy as np
import sklearn

In [5]:
from google.colab import files
uploaded = files.upload()

Saving titanic.csv to titanic.csv

In [6]:
import io
titanic = pd.read_csv(io.BytesIO(uploaded['titanic.csv']))

In [7]:
titanic.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [9]:

# now i noticed that age has some "nan" values , so we neeed to do something 
# so according to the codebasics Naive bayes part 1 video , popularly we take the mean of the column and replace those NaN entries with the mean 
#titanic.Age = titanic.Age.fillna(titanic.Age.mean())
#titanic.head(50)

#doing the above gave 80%ish accuracy , so im trying to drop all rows with NAN values
titanic = titanic.dropna()

In [10]:
len(titanic)

183

In [12]:
y = titanic['Survived']
y.head()

1     1
3     1
6     0
10    1
11    1
Name: Survived, dtype: int64

In [13]:
X = titanic[['Pclass','Sex' , 'Age','Fare']]
X.head(50)

     Pclass     Sex   Age      Fare
1         1  female  38.0   71.2833
3         1  female  35.0   53.1000
6         1    male  54.0   51.8625
10        3  female   4.0   16.7000
11        1  female  58.0   26.5500
21        2    male  34.0   13.0000
23        1    male  28.0   35.5000
27        1    male  19.0  263.0000
52        1  female  49.0   76.7292
54        1    male  65.0   61.9792
62        1    male  45.0   83.4750
66        2  female  29.0   10.5000
75        3    male  25.0    7.6500
88        1  female  23.0  263.0000
92        1    male  46.0   61.1750
96        1    male  71.0   34.6542
97        1    male  23.0   63.3583
102       1    male  21.0   77.2875
110       1    male  47.0   52.0000
118       1    male  24.0  247.5208
123       2  female  32.5   13.0000
124       1    male  54.0   77.2875
136       1  female  19.0   26.2833
137       1    male  37.0   53.1000
139       1    male  24.0   79.2000
148       2    male  36.5   26.0000
151       1  female  22.0   66.6000
170       1    male  61.0   33.5000
174       1    male  56.0   30.6958
177       1  female  50.0   28.7125
183       2    male   1.0   39.0000
193       2    male   3.0   26.0000
194       1  female  44.0   27.7208
195       1  female  58.0  146.5208
205       3  female   2.0   10.4625
209       1    male  40.0   31.0000
215       1  female  31.0  113.2750
218       1  female  32.0   76.2917
224       1    male  38.0   90.0000
230       1  female  35.0   83.4750
245       1    male  44.0   90.0000
248       1    male  37.0   52.5542
251       3  female  29.0   10.4625
252       1    male  62.0   26.5500
257       1  female  30.0   86.5000
262       1    male  52.0   79.6500
263       1    male  40.0    0.0000
268       1  female  58.0  153.4625
269       1  female  35.0  135.6333
273       1    male  37.0   29.7000

In [14]:
len(X)

183

In [15]:
X.head(50)

     Pclass     Sex   Age      Fare
1         1  female  38.0   71.2833
3         1  female  35.0   53.1000
6         1    male  54.0   51.8625
10        3  female   4.0   16.7000
11        1  female  58.0   26.5500
21        2    male  34.0   13.0000
23        1    male  28.0   35.5000
27        1    male  19.0  263.0000
52        1  female  49.0   76.7292
54        1    male  65.0   61.9792
62        1    male  45.0   83.4750
66        2  female  29.0   10.5000
75        3    male  25.0    7.6500
88        1  female  23.0  263.0000
92        1    male  46.0   61.1750
96        1    male  71.0   34.6542
97        1    male  23.0   63.3583
102       1    male  21.0   77.2875
110       1    male  47.0   52.0000
118       1    male  24.0  247.5208
123       2  female  32.5   13.0000
124       1    male  54.0   77.2875
136       1  female  19.0   26.2833
137       1    male  37.0   53.1000
139       1    male  24.0   79.2000
148       2    male  36.5   26.0000
151       1  female  22.0   66.6000
170       1    male  61.0   33.5000
174       1    male  56.0   30.6958
177       1  female  50.0   28.7125
183       2    male   1.0   39.0000
193       2    male   3.0   26.0000
194       1  female  44.0   27.7208
195       1  female  58.0  146.5208
205       3  female   2.0   10.4625
209       1    male  40.0   31.0000
215       1  female  31.0  113.2750
218       1  female  32.0   76.2917
224       1    male  38.0   90.0000
230       1  female  35.0   83.4750
245       1    male  44.0   90.0000
248       1    male  37.0   52.5542
251       3  female  29.0   10.4625
252       1    male  62.0   26.5500
257       1  female  30.0   86.5000
262       1    male  52.0   79.6500
263       1    male  40.0    0.0000
268       1  female  58.0  153.4625
269       1  female  35.0  135.6333
273       1    male  37.0   29.7000

In [17]:
dummies = pd.get_dummies(X.Sex)
dummies.head(4)

    female  male
1        1     0
3        1     0
6        0     1
10       1     0

In [18]:
X = pd.concat([X, dummies], axis = 'columns')
X.head()

    Pclass     Sex   Age     Fare  female  male
1        1  female  38.0  71.2833       1     0
3        1  female  35.0  53.1000       1     0
6        1    male  54.0  51.8625       0     1
10       3  female   4.0  16.7000       1     0
11       1  female  58.0  26.5500       1     0

In [19]:
#now dropping SEX and Female Column 
X.drop(['Sex',"female"] , axis = "columns" , inplace = True)

X.head(10)

    Pclass   Age      Fare  male
1        1  38.0   71.2833     0
3        1  35.0   53.1000     0
6        1  54.0   51.8625     1
10       3   4.0   16.7000     0
11       1  58.0   26.5500     0
21       2  34.0   13.0000     1
23       1  28.0   35.5000     1
27       1  19.0  263.0000     1
52       1  49.0   76.7292     0
54       1  65.0   61.9792     1

In [20]:
X = X.astype({"Age":int,"Fare":int})
# convert column "a" to int64 dtype and "b" to complex type
#df = df.astype({"a": int, "b": complex})
X.head(10)

    Pclass  Age  Fare  male
1        1   38    71     0
3        1   35    53     0
6        1   54    51     1
10       3    4    16     0
11       1   58    26     0
21       2   34    13     1
23       1   28    35     1
27       1   19   263     1
52       1   49    76     0
54       1   65    61     1

In [21]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size = 0.2 , random_state = 1 )

In [22]:
from sklearn import tree
model = tree.DecisionTreeClassifier()
model.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [23]:
model.score(X_test , y_test)

0.7567567567567568